# ETS: Evapotranspiration Segments package file created on 4/10/2015 by ModelMuse version 3.5.1.0.
 1 -1 0 1   # DataSet 1: NETSOP IEVTCB, NPETS, NETSEG
 1 1 1 -1 1 # Data Set 4: INETSS INETSR INETSX [INIETS [INSGDF]] Stress period 1
 constant 900.0      # Data Set 5: ETSS
 constant 0.007      # Data Set 6: ETSR
 constant 20.0       # Data Set 8: ETSX
 -1 -1 -1 -1 1       # Data Set 4: INETSS INETSR INETSX [INIETS [INSGDF]] Stress period 2
 -1 -1 -1 -1 1       # Data Set 4: INETSS INETSR INETSX [INIETS [INSGDF]] Stress period 3
 -1 -1 -1 -1 1       # Data Set 4: INETSS INETSR INETSX [INIETS [INSGDF]] Stress period 4
 -1 -1 -1 -1 1       # Data Set 4: INETSS INETSR INETSX [INIETS [INSGDF]] Stress period 5
