BEGIN ATTRIBUTES
  NAMES ETRATE MYEVTMULT
  METHODS STEPWISE STEPWISE
  SFACS .5 2.0
END ATTRIBUTES

BEGIN TIMESERIES
# time    etrate myevtmult
   0.0     0.02       0.5
   4.0     0.02       0.5
END TIMESERIES
